default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails
  password: rails
  host: localhost

development:
  <<: *default
  database: LoginMock

test:
  <<: *default
  database: LoginMock

production:
  <<: *default
  database: LoginMock
  host: heroku.com
